server:
  port: 8080
spring:
  application:
    name: "FreedomRoute"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@cluster0.veguzyx.mongodb.net/sofkaU?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  swagger-ui:
    path: "/api/swagger-ui.html"